server:
  port: 7600

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: LTAI4G4yjXus5B7Ax7RCMJSZ
      secret-key: qZXfS1w4cHToddFepL70NVMz64x6nA
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-muke
      sms:
        key-id: LTAI4G1Z6H6VjbfF6pSnNQkw
        key-secret: Cld7SlJWeKFb0SqjYThduUY8whQ9Up
        template-code: SMS_208626070
        sign-name: 小码客博客网站
