server:
  port: 7600

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8111
        port: 8719
    alicloud:
      access-key: LTAI4G4yjXus5B7Ax7RCMJSZ
      secret-key: qZXfS1w4cHToddFepL70NVMz64x6nA
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-muke
      sms:
        key-id: LTAI4G1Z6H6VjbfF6pSnNQkw
        key-secret: Cld7SlJWeKFb0SqjYThduUY8whQ9Up
        template-code: SMS_208626070
        sign-name: 小码客博客网站
  redis:
    host: 192.168.56.10
  zipkin:
    # zipkin服务器地址
    base-url: http://192.168.56.10:9411/
    # 关闭zipkin的服务发现，否则spring cloud会将url作为服务名
    discovery-client-enabled: false
    # 设置http方式传输数据
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1 # 设置sleuth的采样率，默认为0.1，即10%
# 健康检查暴露的端点配置
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 开启debug日志
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug
