server:
  port: 8000

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8111
        port: 8719
  rabbitmq:
    host: 192.168.56.10
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    host: 192.168.56.10
  # 异步任务线程池设置
  task:
    execution:
      pool:
        max-size: 20
        queue-capacity: 100
  session:
    store-type: redis
  zipkin:
    # zipkin服务器地址
    base-url: http://192.168.56.10:9411/
    # 关闭zipkin的服务发现，否则spring cloud会将url作为服务名
    discovery-client-enabled: false
    # 设置http方式传输数据
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1 # 设置sleuth的采样率，默认为0.1，即10%
# 健康检查暴露的端点配置
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 开启debug日志
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug
