server:
  port: 88

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/pms/**
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/oms/**
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/oms/**
        - id: service-coupon
          uri: lb://service-coupon
          predicates:
            - Path=/sms/**
        - id: service-member
          uri: lb://service-member
          predicates:
            - Path=/ums/**

