server:
  port: 7000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8111
        port: 8719
  # 开发时，关闭thymeleaf页面缓存
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
  cache:
    type: redis
    redis:
      # 超时时间 毫秒单位
      time-to-live: 60000
      # 设置key前缀，不设置就是缓存分区名
      #key-prefix: CACHE_
      # 使用key前缀
      use-key-prefix: true
      # 缓存null值，防止缓存穿透
      cache-null-values: true
  session:
    store-type: redis
  zipkin:
    # zipkin服务器地址
    base-url: http://192.168.56.10:9411/
    # 关闭zipkin的服务发现，否则spring cloud会将url作为服务名
    discovery-client-enabled: false
    # 设置http方式传输数据
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1 # 设置sleuth的采样率，默认为0.1，即10%

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

# 开启debug日志
logging:
  level:
    com.muke.gulimall.pms.dao: debug
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug

# 线程池配置
gulimall:
  thread:
    pool:
      core-size: 20
      max-count: 200
      keep-alive-time: 10000

# 健康检查暴露的端点配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true